### PR TITLE
Only implement `Send + Sync` if `T` implements `Send + Sync`

### PR DESCRIPTION
**Pull request by ghost**
Similar to [`RwLock`](https://doc.rust-lang.org/std/sync/struct.RwLock.html).

EDIT: Note that nightly is broken because the cargo build is bad. Same result on my local computer.

### CODE REVIEW

**Comment by kvark** [comment]
Why is it not `T:Send` for `Send` and `T:Sync` for `Sync`?

**Comment by ghost** [comment]
The reason for this is the same as on `std::sync::RwLock`, which also has the same `Send + Sync` impl:

> The type parameter `T` represents the data that this lock protects. It is required that `T` satisfies `Send` to be shared across threads and `Sync` to allow concurrent access through readers. The RAII guards returned from the locking methods implement `Deref` (and `DerefMut` for the `write` methods) to allow access to the contained of the lock.

Or, in other words, since it provides concurrent read access, it cannot provide `Send` unless the underlying type is `Sync`. For example, this wouldn't be the case 
 for a mutex, which provides single readers/writers.

**Comment by ghost** [comment]
Also, note that this is a potential motivation for adding ticketed mutexes. It allows underlying types to only require implementing `Send` and not `Sync`.

**Comment by ghost** [comment]
Well, I changed my username and broke this PR. I'll re-open.

**Pull request closed without merging**
